# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.16.14
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.0.1
maven_group=net.IAteMinecraft.watchdog
archives_base_name=watchdog

# Dependencies
fabric_version=0.92.6+1.20.1

# Midnight Lib
#midnightlib_version = 1.4.1-fabric

# Forge Config API
forge_config_api_version=8.0.2